# Generated by Django 4.2.4 on 2023-08-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.EmailField(blank=True, max_length=254)),
                ('content', models.CharField(max_length=70)),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('num_reaction', models.PositiveIntegerField()),
                ('num_repost', models.PositiveIntegerField()),
                ('num_comments', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('registration_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reposteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTI.publicacion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTI.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTI.usuario'),
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=5)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTI.publicacion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTI.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('total_comments', models.PositiveIntegerField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTI.publicacion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTI.usuario')),
            ],
        ),
    ]
