# Generated by Django 4.2.4 on 2023-09-11 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogTI', '0002_customuser_alter_comentario_total_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ('-publication_date',)},
        ),
        migrations.AddField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(default=1, max_length=25, unique=True, unique_for_date='publication_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
